[package]
name = "webfinger"
version = "0.1.0"
authors = ["A. Malacoda <adrian.malacoda@monarch-pass.net>", "kenkeiras <kenkeiras@codigoparallevar.com>"]

[dependencies]
log = "0.4.1"
env_logger = "0.5.3"
url = "1.6.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
reqwest = "0.8.4"
