[package]
name = "webfinger"
version = "0.1.0"
authors = ["A. Malacoda <adrian.malacoda@monarch-pass.net>", "kenkeiras <kenkeiras@codigoparallevar.com>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
url = "1.5.1"
serde = "1.0.14"
serde_derive = "1.0.14"
serde_json = "1.0.3"
reqwest = "0.7.3"
