[package]
name = "webfinger"
version = "0.1.0"
authors = ["Adrian Malacoda <adrian.malacoda@monarch-pass.net>", "kenkeiras <kenkeiras@codigoparallevar.com>"]

[dependencies]
log = "0.3.6"
env_logger = "0.4.0"
url = "1.4.0"
serde = "0.6.7" # "0.9.13"
serde_json = "0.6.0" # "0.9.10"
hyper = "0.7.1"
